### ISSUE TITLE
Button continue its state after a single click

### ISSUE THREAD

**Issue by sarathlal-old** [mazzorini/Markdanchor#1]
It works on anchor 0.9.2.
But after click one icon, it can't reset from button. The button is continue as selected.
Is it a bug?
I think we want to reset from that button & then go to post content form!

**Comment by mazzorini** [comment]
It is not a bug, the same "problem" comes with the standard editor.

**Comment by mazzorini** [comment]
i added a script (now you jump to the end of line after klick a button) and i removed bootstrap.min.js (no need for dropdowns) 
https://github.com/mazzo-/Markdanchor/commit/6d59cf81e2b8b7bdcd1b91a16de3463a5ef129a5
